### ISSUE TITLE
AFBR-S50 v1.4.4 Crash

### ISSUE THREAD

**Issue by Honza281** [Broadcom/AFBR-S50-API#22]
Hello,

Upon launching the application, an error window similar to the one depicted in the attached image pops up. Additionally, the following log appears in the bottom section of the program:

_Status/Log: Fatal: An unhandled exception occured! Vstupní řetězec nemá správný formát. v System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)_

After dismissing the dialogue, the program terminates abruptly. It's worth noting that version 1.3.5 of the program functions properly; however, it seems to lack compatibility with the board.

Could you please provide assistance in resolving this issue? Any guidance or recommendations would be greatly appreciated.

![afbr50](https://github.com/Broadcom/AFBR-S50-API/assets/58737587/ad6671ce-9353-4b0d-8525-bf00b5bf99c5)
![afbr50 crash](https://github.com/Broadcom/AFBR-S50-API/assets/58737587/6c03d541-2294-4529-834e-21b0a96a751f)

Thank you.
Jan

**Comment by c-berger** [comment]
Hi Jan,

sorry for the inconvenience. There is a known issue in the current Explorer (v1.4.4) that happens when parsing data that has other decimal delimiter than a dot (`.`). We have fixed that issue in the next release of our GUI (v1.5.6) which is currently in the upload phase and should appear within the next days on the [Broadcom webpage](https://www.broadcom.com/products/optical-sensors/time-of-flight-3d-sensors/afbr-s50-fek) (under "Downloads").

Meanwhile, you could change the regional settings to use a dot as a decimal separator.  An easy way to do this is to tap the windows key and type "region", then open the region settings and change the regional format to English (United States).
![image](https://github.com/Broadcom/AFBR-S50-API/assets/71664347/8c6be26f-3adc-4b22-a50b-c723ed1de4b2)

Alternatively you could use the "Additional date, time & regional settings" to only change the number format. 
![image](https://github.com/Broadcom/AFBR-S50-API/assets/71664347/b5d505f0-17a0-4b60-a6ca-2653a49558ba)

Best regards!
